[project]
name = "media-mover"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "autoflake>=2.3.3",
    "customtkinter>=5.2.2",
    "ffmpeg>=1.4",
    "ffmpeg-python>=0.2.0",
    "pillow>=12.0.0",
    "pillow-heif>=1.1.1",
    "pyexiftool>=0.5.6",
    "pyinstaller>=6.21.0",
    "pymobiledevice3>=8.2.4",
]
